name: misskey_mfm
version: 0.0.1
environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"
description: A new Flutter package project.
dependencies:
  flutter:
    sdk: flutter
  petitparser: ^6.1.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  test: ^1.26.2
flutter: null
