name: misskey_mfm_parser
version: 1.0.0
environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"
description: mfm parser rewritten in Dart.
dependencies:
  emoji_regex: ^0.0.5
  flutter:
    sdk: flutter
  petitparser: ^7.0.1
dev_dependencies:
  custom_lint: ^0.8.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.33.0
  pubspec_dependency_sorter: ^1.0.5
  test: ^1.26.2
flutter: null
